name: Latest Changes

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  latest-changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tiangolo/latest-changes@0.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}